### ISSUE TITLE
Edge can't handle global.css input[type="range"] styling

### ISSUE THREAD

**Issue by jutunen** [sveltejs/template#64]
This is most likely an Edge issue but I'll report this anyway.

global.css has following definition:

```css
input[type="range"] {
	height: 0;
}
```
Setting the height to 0 makes range slider thumb completely invisible on Edge.
In general, why is that style definition in global.css at all?
